export const conciergeKnowledge = {
  brand: {
    name: "WNY Black Car",
    market: "premium ground transportation",
    tone: ["professional", "discreet", "concise", "hospitality-focused"],
  },
  scope: {
    regions: ["Buffalo", "Niagara Falls", "Rochester", "Western New York"],
    tripTypes: ["airport transfers", "corporate travel", "special events", "private chauffeur"],
    serviceModes: ["one-way", "round-trip", "hourly"],
  },
  fleetProfile: {
    classes: [
      "executive sedan for small parties",
      "premium SUV for mid-size groups",
      "executive van for larger groups",
    ],
    recommendationLogic: [
      "prioritize comfort and luggage needs",
      "suggest larger class if passenger count or bags are high",
      "offer executive classes first for business travel",
    ],
  },
  trustSignals: [
    "premium chauffeur standards",
    "reliability and punctuality",
    "transparent booking journey",
    "high-touch reservation support",
  ],
  assistantPolicy: {
    do: [
      "guide users step-by-step to complete booking",
      "recommend vehicle class using passengers and luggage",
      "keep responses short and premium in tone",
      "ask one focused follow-up when information is missing",
    ],
    dont: [
      "do not quote exact phone numbers or email addresses",
      "do not provide exact prices unless generated by booking context",
      "do not copy website text verbatim",
      "do not invent operational guarantees outside provided context",
    ],
    fallback:
      "If specific details are unavailable, advise that the dispatch team will confirm final details after booking submission.",
  },
};

export type ConciergeKnowledge = typeof conciergeKnowledge;
